### PR TITLE
Adjusting curved link paths based on port Alignment

### PR DESCRIPTION
**Pull request by joezearing**
Uses the Source and Target port Alignment values to make a path that connects to the nodes pointing away.  Old method did not point away from the node if port was on Top or Bottom.

### CODE REVIEW

**Comment by zHaytam** [comment]
Hi, thank you for the great PR!
I'm wondering if we should also handle the other alignements (TopLeft, TopRight, ...), what do you think ?

**Comment by joezearing** [comment]
Makes sense.  I added handling for all the combinations now and did a bit of refactoring.  Also adjusted the default styles in the demo to support all the port alignments.

**Comment by zHaytam** [comment]
With your latest update, there is a weird behavior when creating/dragging a new link. Seems like the added margin is the issue, if I understand the difference between your previous code and the new one?

**Comment by joezearing** [comment]
Yes, the new update aims to ensure that every link points directly away from the node. If the center point of the line is within the defined margin, then it uses that margin minimum.  It helps to get the line to stick out away from the node if it turns directly around and goes the other direction.

**Comment by zHaytam** [comment]
Oh, got it now, thank you. It does look nice when the nodes are on opposite sides.
Although I'm not a fan of how it looks when you first create the link because it's so far from the mouse position. I'm trying to find a solution right now.

**Comment by zHaytam** [comment]
What do you think about only including the margin when the link is attached?

**Comment by joezearing** [comment]
What do you think of that?  It will use the min of (the distance between the source point and the center point) and (125).

**Comment by zHaytam** [comment]
Looking good! Excellent job, thank you again!
Will be merging soon.

**Comment by joezearing** [comment]
Awesome! Thanks!

**Pull request merged**
